name: Email Step Test

on:
  push:
    branches:
      - master  # or 'master' if that's your default branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: 23f1002114@ds.study.iitm.ac.in
        run: echo "Hello, world!"
